# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 615d1874b7b78f73e979041ecb6f1ddc0c471d9cdfec4e8b8de5f24181ae1a4aa4907557cf4ece3da97d0801b9e667f55df37a104f0092760a74696631f5defd

test:
  secret_key_base: 3c47d20fd9c23d33053e5e5868c8d9097c7072e9568f53f79b9c912182c693b68fb2f6b0421d8139239e86add7d191a821e5233b078002a744cf9e09e5e7c8fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
